track_topic: /tracking
cmd_vel_topic: /cmd_vel
desired_xy_scale: 3.0
desired_center_x: 450
desired_center_y: 300
desired_bbox_x_size: 400
desired_bbox_y_size: 400
fx_pid:
  p: 7.0
  i: 0.01
  d: 0.4
  i_clamp_max: 0.2
  i_clamp_min: -0.2
fy_pid:
  p: 0.01
  i: 0.002
  d: 0.002
  i_clamp_max: 0.5
  i_clamp_min: -0.5
fz_pid:
  p: 0.008
  i: 0.00001
  d: 0.004
  i_clamp_max: 2.0
  i_clamp_min: -2.0
